In [1]:
import pandas as pd

output__path = "../Outputs/"
input_path_note = "../data/mimic-iv-note/2.2/note/"

ca_patients_path = f"{output__path}ca_patients_filtered.csv"
disc_filtered_path = f"{output__path}discharge_filtered.csv"

In [2]:
ca_patients = pd.read_csv(ca_patients_path)
discharge_filtered = pd.read_csv(disc_filtered_path)

df_path = "../Outputs/final_structured_dataset.csv"
df_final = pd.read_csv(df_path)

In [3]:
ca_patients.head()

,subject_id,hadm_id,icd_code,stay_id,intime,outtime,los,gender,anchor_age,anchor_year,anchor_year_group,dischtime,deathtime,dod,survival_status
0,10001884,26184834,I469,37510196,2131-01-11 04:20:05,2131-01-20 08:27:30,9.171817,F,68,2122,2008 - 2010,2131-01-20 05:15:00,2131-01-20 05:15:00,2131-01-20 05:15:00,1
1,10009823,22096005,I469,31805686,2150-12-06 06:46:10,2150-12-06 20:33:52,0.574792,F,45,2150,2020 - 2022,2150-12-06 14:22:00,2150-12-06 14:22:00,2150-12-06 14:22:00,1
2,10010471,29842315,I462,32119961,2155-12-02 20:33:00,2155-12-07 18:19:18,4.907153,F,89,2155,2014 - 2016,2155-12-07 15:30:00,2155-12-07 15:30:00,2155-12-07 15:30:00,1
3,10013569,27993048,4275,38857852,2167-11-26 16:26:07,2167-12-05 16:53:53,9.019282,F,54,2165,2008 - 2010,2167-12-25 14:53:00,NaN,NaN,0
4,10021454,29492087,I469,33300154,2125-03-17 02:41:26,2125-03-24 20:18:57,7.734387,M,88,2125,2020 - 2022,2125-03-24 16:43:00,2125-03-24 16:43:00,2125-03-24 16:43:00,1

In [4]:
df_final.head()

,subject_id,hadm_id,stay_id,gender,anchor_age,survival_status,HR,SBP,DBP,MBP,...,pH,hypertension,congestive_heart_failure,myocardial_infarction,diabetes_mellitus,copd,GCS_Total,received_ventilation,received_epinephrine,received_dopamine
0,10001884,26184834,37510196,0,68,1,71.392857,123.730769,75.320000,88.747692,...,7.340000,1,0,0,0,1,7.625,1,0,1
1,10009823,22096005,31805686,0,45,1,106.461538,111.900000,73.545455,85.210606,...,7.190000,1,0,0,0,0,3.000,1,0,0
2,10010471,29842315,32119961,0,89,1,86.920000,104.840000,54.280000,68.506667,...,7.307475,1,1,1,0,1,15.000,0,0,0
3,10013569,27993048,38857852,0,54,0,80.285714,108.640000,59.080000,72.800000,...,7.350000,1,1,0,0,0,15.000,0,0,1
4,10021454,29492087,33300154,1,88,1,57.920000,110.854130,48.005116,68.954787,...,7.362000,1,0,0,0,0,4.500,0,0,0

In [5]:
discharge_filtered.head()

,note_id,subject_id,hadm_id,note_type,note_seq,charttime,storetime,text
0,10001884-DS-38,10001884,26184834,DS,38,2131-01-20 00:00:00,2131-01-20 09:41:00,\nName: ___ Unit No: ___\n \nA...
1,10010471-DS-22,10010471,29842315,DS,22,2155-12-07 00:00:00,2155-12-09 10:22:00,\nName: ___ Unit No: ___\n ...
2,10013569-DS-10,10013569,27993048,DS,10,2167-12-25 00:00:00,2167-12-25 16:07:00,\nName: ___ Unit No: ___\n...
3,10024982-DS-20,10024982,25154057,DS,20,2203-10-11 00:00:00,2203-10-12 00:21:00,\nName: ___ Unit No: ___...
4,10026161-DS-7,10026161,24614671,DS,7,2133-11-15 00:00:00,2133-11-18 20:57:00,\nName: ___ Unit No: ___\n ...

In [6]:
discharge_filtered.subject_id.nunique()

1618

In [7]:
df_final.subject_id.nunique()

2307

In [8]:
discharge_filtered.hadm_id.nunique()

1618

In [13]:
df_combined = discharge_filtered.merge(df_final, how='inner', on=['hadm_id', 'subject_id'])

In [14]:
df_combined.shape

(1618, 45)

In [15]:
df_combined[['text', 'Lactate']]

                                                   text   Lactate
0      \nName:  ___             Unit No:   ___\n \nA...  1.300000
1      \nName:  ___                Unit No:   ___\n ...  2.150000
2      \nName:  ___                 Unit No:   ___\n...  0.091765
3      \nName:  ___                   Unit No:   ___...  4.600000
4      \nName:  ___                Unit No:   ___\n ...  5.508333
...                                                 ...       ...
1613   \nName:  ___              Unit No:   ___\n \n...  1.100000
1614   \nName:  ___                  Unit No:   ___\...  1.150000
1615   \nName:  ___                    Unit No:   __...  0.800000
1616   \nName:  ___                    Unit No:   __...  3.757143
1617   \nName:  ___                    Unit No:   __...  2.593387

[1618 rows x 2 columns]

In [16]:
df_combined

,note_id,subject_id,hadm_id,note_type,note_seq,charttime,storetime,text,stay_id,gender,...,pH,hypertension,congestive_heart_failure,myocardial_infarction,diabetes_mellitus,copd,GCS_Total,received_ventilation,received_epinephrine,received_dopamine
0,10001884-DS-38,10001884,26184834,DS,38,2131-01-20 00:00:00,2131-01-20 09:41:00,\nName: ___ Unit No: ___\n \nA...,37510196,0,...,7.340000,1,0,0,0,1,7.625000,1,0,1
1,10010471-DS-22,10010471,29842315,DS,22,2155-12-07 00:00:00,2155-12-09 10:22:00,\nName: ___ Unit No: ___\n ...,32119961,0,...,7.307475,1,1,1,0,1,15.000000,0,0,0
2,10013569-DS-10,10013569,27993048,DS,10,2167-12-25 00:00:00,2167-12-25 16:07:00,\nName: ___ Unit No: ___\n...,38857852,0,...,7.350000,1,1,0,0,0,15.000000,0,0,1
3,10024982-DS-20,10024982,25154057,DS,20,2203-10-11 00:00:00,2203-10-12 00:21:00,\nName: ___ Unit No: ___...,37919901,1,...,7.350000,0,0,1,0,1,7.566667,1,0,0
4,10026161-DS-7,10026161,24614671,DS,7,2133-11-15 00:00:00,2133-11-18 20:57:00,\nName: ___ Unit No: ___\n ...,39625056,1,...,7.234286,0,1,1,0,0,6.666667,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1613,19969137-DS-15,19969137,20917922,DS,15,2143-03-31 00:00:00,2143-04-02 13:46:00,\nName: ___ Unit No: ___\n \n...,31637227,0,...,7.360000,0,1,0,0,0,9.500000,1,0,0
1614,19975796-DS-6,19975796,25848942,DS,6,2148-12-14 00:00:00,2148-12-15 13:59:00,\nName: ___ Unit No: ___\...,31651964,0,...,7.250000,1,0,0,0,1,12.375000,1,0,0
1615,19983257-DS-23,19983257,21588174,DS,23,2166-06-19 00:00:00,2166-06-19 22:04:00,\nName: ___ Unit No: __...,30916791,1,...,7.400000,0,1,0,0,1,14.857143,1,0,0
1616,19990427-DS-3,19990427,29695607,DS,3,2182-01-24 00:00:00,2182-01-26 07:07:00,\nName: ___ Unit No: __...,34058245,0,...,7.279091,1,0,0,0,0,3.166667,1,1,0
1617,19993336-DS-12,19993336,23077223,DS,12,2171-10-04 00:00:00,2171-10-04 19:10:00,\nName: ___ Unit No: __...,36483324,0,...,7.450000,1,1,1,0,0,14.500000,0,0,0